# Generated by Django 4.2.6 on 2023-11-08 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_identification_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_ident_type', models.IntegerField()),
                ('ident_number', models.CharField(max_length=15)),
                ('id_exp_city', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=50)),
                ('id_user', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
