# Generated by Django 4.2.6 on 2023-11-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=110),
        ),
    ]
