# Generated by Django 4.2.6 on 2023-11-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_cities_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='firs_name',
            field=models.CharField(max_length=40),
        ),
    ]
